// ── PDF Export ─────────────────────────────────────────────────────────────
// Generates a BRSR-compatible GHG Inventory PDF report using jsPDF.

import jsPDF from 'jspdf';
import type { InventoryResult, BrsrOutput } from '@/lib/calc-engine/types';

interface PdfExportData {
  organisation: { name: string; sector: string; state: string };
  period: { startDate: string; endDate: string };
  result: InventoryResult;
  brsr: BrsrOutput;
  methodology: string;
}

const MARGIN = 20;
const PAGE_WIDTH = 210; // A4
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 6;
const FONT_SIZE_TITLE = 18;
const FONT_SIZE_HEADING = 12;
const FONT_SIZE_BODY = 9;
const FONT_SIZE_SMALL = 8;

function fmt(n: number | null | undefined, decimals = 2): string {
  if (n == null) return 'N/A';
  return n.toLocaleString('en-IN', { maximumFractionDigits: decimals });
}

function addFooter(doc: jsPDF, pageNum: number) {
  const y = 285;
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(
    `Generated by GHG Tool | ${new Date().toLocaleDateString('en-IN')}`,
    MARGIN,
    y,
  );
  doc.text(`Page ${pageNum}`, PAGE_WIDTH - MARGIN, y, { align: 'right' });
}

function checkPageBreak(doc: jsPDF, y: number, needed: number, pageNum: { value: number }): number {
  if (y + needed > 275) {
    addFooter(doc, pageNum.value);
    doc.addPage();
    pageNum.value++;
    return 30;
  }
  return y;
}

function drawTableRow(
  doc: jsPDF,
  y: number,
  cols: { text: string; x: number; width: number; align?: 'left' | 'right' }[],
  isHeader: boolean,
) {
  const rowHeight = 8;
  if (isHeader) {
    doc.setFillColor(245, 245, 245);
    doc.rect(MARGIN, y - 1, CONTENT_WIDTH, rowHeight, 'F');
    doc.setFontSize(FONT_SIZE_SMALL);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(80, 80, 80);
  } else {
    doc.setFontSize(FONT_SIZE_SMALL);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(40, 40, 40);
  }

  for (const col of cols) {
    const xPos = col.align === 'right' ? col.x + col.width - 2 : col.x;
    doc.text(col.text, xPos, y + 4, { align: col.align ?? 'left' });
  }

  // Bottom border
  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y + rowHeight - 1, MARGIN + CONTENT_WIDTH, y + rowHeight - 1);

  return y + rowHeight;
}

function addSectionHeading(doc: jsPDF, y: number, title: string): number {
  doc.setFontSize(FONT_SIZE_HEADING);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text(title, MARGIN, y);
  // Underline
  doc.setDrawColor(15, 118, 110); // teal-700
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y + 2, MARGIN + doc.getTextWidth(title), y + 2);
  return y + 10;
}

export function generatePdfReport(data: PdfExportData): void {
  const { organisation, period, result, brsr, methodology } = data;
  const doc = new jsPDF('portrait', 'mm', 'a4');
  const pageNum = { value: 1 };
  let y = 30;

  // ── Title ──────────────────────────────────────────────────────────────
  doc.setFontSize(FONT_SIZE_TITLE);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('GHG Inventory Report', MARGIN, y);
  y += 8;

  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(organisation.name || 'Unnamed Organisation', MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(
    `Period: ${period.startDate || '—'} to ${period.endDate || '—'}`,
    MARGIN,
    y,
  );
  y += LINE_HEIGHT;
  doc.text(
    `Sector: ${organisation.sector} | State: ${organisation.state || '—'}`,
    MARGIN,
    y,
  );
  y += 12;

  // Separator
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 10;

  // ── Section 1: Executive Summary ───────────────────────────────────────
  y = addSectionHeading(doc, y, '1. Executive Summary');

  const summaryItems = [
    ['Grand Total Emissions', `${fmt(result.grandTotal, 4)} tCO2e`],
    ['Scope 1 (Direct)', `${fmt(result.scope1.total, 4)} tCO2e`],
    ['Scope 2 (Electricity)', `${fmt(result.scope2Location.total, 4)} tCO2e`],
    ['Scope 3 (Value Chain)', `${fmt(result.scope3.total, 4)} tCO2e`],
    ['Total Energy Consumed', `${fmt(result.energyConsumedGj)} GJ`],
    ['Renewable Energy Share', `${fmt(result.renewablePercent)}%`],
  ];

  for (const [label, value] of summaryItems) {
    doc.setFontSize(FONT_SIZE_BODY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text(label, MARGIN + 2, y);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 30, 30);
    doc.text(value, MARGIN + 100, y);
    y += LINE_HEIGHT;
  }
  y += 6;

  // ── Section 2: BRSR Principle 6 Disclosure ─────────────────────────────
  y = checkPageBreak(doc, y, 80, pageNum);
  y = addSectionHeading(doc, y, '2. BRSR Principle 6 Disclosure');

  const brsrRows: [string, string][] = [
    ['Total Scope 1 Emissions (tCO2e)', fmt(brsr.scope1Total, 4)],
    ['Total Scope 2 Emissions (tCO2e)', fmt(brsr.scope2Total, 4)],
    ['Total Scope 3 Emissions (tCO2e)', fmt(brsr.scope3Total, 4)],
    ['Intensity per Rupee of Turnover', fmt(brsr.intensityPerTurnover, 6)],
    ['Intensity per Unit of Product', fmt(brsr.intensityPerProduct, 6)],
    ['Total Energy Consumed (GJ)', fmt(brsr.totalEnergyGj, 2)],
    ['Renewable Energy (%)', fmt(brsr.renewablePercent, 2)],
  ];

  // Table header
  y = drawTableRow(doc, y, [
    { text: 'Field', x: MARGIN, width: 110 },
    { text: 'Value', x: MARGIN + 110, width: 60, align: 'right' },
  ], true);

  for (const [field, value] of brsrRows) {
    y = checkPageBreak(doc, y, 10, pageNum);
    y = drawTableRow(doc, y, [
      { text: field, x: MARGIN, width: 110 },
      { text: value, x: MARGIN + 110, width: 60, align: 'right' },
    ], false);
  }
  y += 8;

  // ── Section 3: Emission Breakdown ──────────────────────────────────────
  y = checkPageBreak(doc, y, 60, pageNum);
  y = addSectionHeading(doc, y, '3. Emission Breakdown by Scope');

  const scopes = [
    { label: 'Scope 1', data: result.scope1 },
    { label: 'Scope 2', data: result.scope2Location },
    { label: 'Scope 3', data: result.scope3 },
  ];

  for (const scope of scopes) {
    y = checkPageBreak(doc, y, 20 + scope.data.categories.length * 8, pageNum);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(50, 50, 50);
    doc.text(`${scope.label}: ${fmt(scope.data.total, 4)} tCO2e`, MARGIN + 2, y);
    y += 7;

    for (const cat of scope.data.categories) {
      doc.setFontSize(FONT_SIZE_SMALL);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(80, 80, 80);
      doc.text(`  ${cat.category}`, MARGIN + 4, y);
      doc.text(fmt(cat.total, 4), MARGIN + 130, y, { align: 'right' });
      y += LINE_HEIGHT;
    }
    y += 4;
  }

  // ── Section 4: Top 5 Emission Sources ──────────────────────────────────
  y = checkPageBreak(doc, y, 60, pageNum);
  y = addSectionHeading(doc, y, '4. Top Emission Sources');

  y = drawTableRow(doc, y, [
    { text: 'Source', x: MARGIN, width: 90 },
    { text: 'CO2e (t)', x: MARGIN + 90, width: 40, align: 'right' },
    { text: '% of Total', x: MARGIN + 130, width: 40, align: 'right' },
  ], true);

  const topSources = result.topSources.slice(0, 5);
  for (const src of topSources) {
    y = checkPageBreak(doc, y, 10, pageNum);
    y = drawTableRow(doc, y, [
      { text: src.source, x: MARGIN, width: 90 },
      { text: fmt(src.co2e, 4), x: MARGIN + 90, width: 40, align: 'right' },
      { text: `${fmt(src.percent, 1)}%`, x: MARGIN + 130, width: 40, align: 'right' },
    ], false);
  }
  y += 8;

  // ── Section 5: Data Quality Assessment ─────────────────────────────────
  y = checkPageBreak(doc, y, 50, pageNum);
  y = addSectionHeading(doc, y, '5. Data Quality Assessment');

  const dq = result.dataQuality;
  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  doc.text(`Overall Score: ${dq.overall}/100 (${dq.grade})`, MARGIN + 2, y);
  y += LINE_HEIGHT;
  doc.text(
    `Data points — Primary: ${dq.breakdown.primary}, Secondary: ${dq.breakdown.secondary}, Estimated: ${dq.breakdown.estimated}`,
    MARGIN + 2,
    y,
  );
  y += LINE_HEIGHT + 2;

  if (dq.recommendations.length > 0) {
    doc.setFontSize(FONT_SIZE_SMALL);
    doc.setFont('helvetica', 'bold');
    doc.text('Recommendations:', MARGIN + 2, y);
    y += LINE_HEIGHT;
    doc.setFont('helvetica', 'normal');
    for (const rec of dq.recommendations) {
      y = checkPageBreak(doc, y, 8, pageNum);
      const lines = doc.splitTextToSize(`- ${rec}`, CONTENT_WIDTH - 4);
      doc.text(lines, MARGIN + 4, y);
      y += lines.length * 5;
    }
  }
  y += 6;

  // ── Section 6: Cross-Check Results ─────────────────────────────────────
  if (result.crossCheckWarnings.length > 0) {
    y = checkPageBreak(doc, y, 30, pageNum);
    y = addSectionHeading(doc, y, '6. Cross-Check Results');

    for (const w of result.crossCheckWarnings) {
      y = checkPageBreak(doc, y, 12, pageNum);
      const icon = w.severity === 'error' ? '[ERROR]' : w.severity === 'warning' ? '[WARN]' : '[INFO]';
      doc.setFontSize(FONT_SIZE_SMALL);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(
        w.severity === 'error' ? 220 : w.severity === 'warning' ? 180 : 100,
        w.severity === 'error' ? 50 : w.severity === 'warning' ? 120 : 100,
        50,
      );
      doc.text(icon, MARGIN + 2, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      const lines = doc.splitTextToSize(w.message, CONTENT_WIDTH - 30);
      doc.text(lines, MARGIN + 22, y);
      y += lines.length * 5 + 2;
    }
    y += 6;
  }

  // ── Section 7: Methodology Note ────────────────────────────────────────
  y = checkPageBreak(doc, y, 60, pageNum);
  y = addSectionHeading(doc, y, '7. Methodology Note');

  doc.setFontSize(FONT_SIZE_SMALL);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(70, 70, 70);
  const methLines = doc.splitTextToSize(methodology, CONTENT_WIDTH - 4);
  for (let i = 0; i < methLines.length; i++) {
    y = checkPageBreak(doc, y, 6, pageNum);
    doc.text(methLines[i], MARGIN + 2, y);
    y += 4.5;
  }

  // Final footer
  addFooter(doc, pageNum.value);

  // Trigger download
  const filename = `GHG_Report_${(organisation.name || 'report').replace(/\s+/g, '_')}_${period.startDate || 'draft'}.pdf`;
  doc.save(filename);
}
