// ── Reduction Plan PDF Export ──────────────────────────────────────────────
// Generates a PDF summary of emission reduction recommendations.

import jsPDF from 'jspdf';
import type { RecommendationResult } from '@/lib/rec-engine/types';

const MARGIN = 20;
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 6;

function fmt(n: number | null | undefined, decimals = 1): string {
  if (n == null) return 'N/A';
  return n.toLocaleString('en-IN', { maximumFractionDigits: decimals });
}

function addFooter(doc: jsPDF, pageNum: number) {
  doc.setFontSize(7);
  doc.setTextColor(150, 150, 150);
  doc.text(`Generated by GHG Tool | ${new Date().toLocaleDateString('en-IN')}`, MARGIN, 285);
  doc.text(`Page ${pageNum}`, PAGE_WIDTH - MARGIN, 285, { align: 'right' });
}

function checkPage(doc: jsPDF, y: number, needed: number, pageNum: { val: number }): number {
  if (y + needed > 270) {
    addFooter(doc, pageNum.val);
    doc.addPage();
    pageNum.val++;
    return MARGIN + 10;
  }
  return y;
}

export function generateReductionPlanPdf(data: RecommendationResult) {
  const doc = new jsPDF();
  const pageNum = { val: 1 };
  const { recommendations, combinedImpact: ci } = data;

  // ── Title ──────────────────────────────────────────────────────────────
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42); // zinc-900
  doc.text('Emission Reduction Plan', MARGIN, 30);

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139); // zinc-500
  doc.text(`${recommendations.length} technologies matched · Generated ${new Date().toLocaleDateString('en-IN')}`, MARGIN, 38);

  // ── Impact Summary ─────────────────────────────────────────────────────
  let y = 50;
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Impact Summary', MARGIN, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105);
  const summaryLines = [
    `Baseline Emissions: ${fmt(ci.baselineTotalTonnes)} tCO2e/year`,
    `Potential Reduction: ${fmt(ci.totalReductionTonnes)} tCO2e/year (${fmt(ci.totalReductionPct)}%)`,
    `Post-Reduction: ${fmt(ci.postReductionTotalTonnes)} tCO2e/year`,
    `Total CAPEX: Rs.${fmt(ci.totalCapexMinLakhs, 0)}–${fmt(ci.totalCapexMaxLakhs, 0)} Lakhs`,
    `Annual Savings: Rs.${fmt(ci.totalAnnualSavingMinInr / 100000, 0)}–${fmt(ci.totalAnnualSavingMaxInr / 100000, 0)} Lakhs`,
    `Blended Payback: ${ci.blendedPaybackYears != null ? `${fmt(ci.blendedPaybackYears)} years` : 'N/A'}`,
  ];
  for (const line of summaryLines) {
    doc.text(line, MARGIN, y);
    y += LINE_HEIGHT;
  }

  // ── Technology Table ───────────────────────────────────────────────────
  y += 6;
  y = checkPage(doc, y, 40, pageNum);
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text('Technology Breakdown', MARGIN, y);
  y += 8;

  // Header
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.text('Technology', MARGIN, y);
  doc.text('Category', MARGIN + 52, y);
  doc.text('Reduction (t)', MARGIN + 95, y);
  doc.text('CAPEX (Rs.L)', MARGIN + 125, y);
  doc.text('Payback', MARGIN + 150, y);
  y += 2;
  doc.setDrawColor(228, 228, 231);
  doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
  y += 5;

  doc.setTextColor(30, 41, 59);
  for (const tech of recommendations) {
    y = checkPage(doc, y, 8, pageNum);
    const name = tech.name.length > 24 ? tech.name.substring(0, 24) + '...' : tech.name;
    const cat = tech.category.replace(' - Cross Sector', '').replace('Sector Specific - ', '');
    const shortCat = cat.length > 18 ? cat.substring(0, 18) + '...' : cat;

    doc.setFontSize(8);
    doc.text(name, MARGIN, y);
    doc.text(shortCat, MARGIN + 52, y);
    doc.text(`${fmt(tech.reductionMidTonnes)}`, MARGIN + 95, y);
    doc.text(
      tech.capexMinLakhs != null ? `${fmt(tech.capexMinLakhs, 0)}–${fmt(tech.capexMaxLakhs, 0)}` : 'N/A',
      MARGIN + 125, y,
    );
    doc.text(`${tech.paybackMinYears}–${tech.paybackMaxYears} yrs`, MARGIN + 150, y);
    y += LINE_HEIGHT;
  }

  // ── Sequential Waterfall ───────────────────────────────────────────────
  if (ci.technologySequence.length > 0) {
    y += 8;
    y = checkPage(doc, y, 30, pageNum);
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Reduction Sequence (Sequential)', MARGIN, y);
    y += 3;
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text('Technologies applied to residual emissions in order of payback period', MARGIN, y + 4);
    y += 10;

    doc.setFontSize(8);
    doc.setTextColor(30, 41, 59);
    doc.text(`Baseline: ${fmt(ci.baselineTotalTonnes)} tCO2e`, MARGIN, y);
    y += LINE_HEIGHT;

    for (let i = 0; i < ci.technologySequence.length; i++) {
      y = checkPage(doc, y, 8, pageNum);
      const step = ci.technologySequence[i];
      const name = step.name.length > 30 ? step.name.substring(0, 30) + '...' : step.name;
      doc.text(`${i + 1}. ${name}  -${fmt(step.reductionTonnes)} t  >>  ${fmt(step.residualAfterTonnes)} t`, MARGIN + 4, y);
      y += LINE_HEIGHT;
    }
  }

  // ── Funding Summary ────────────────────────────────────────────────────
  const allSchemes = new Map<string, { name: string; agency: string; subsidy: number | null; status: string }>();
  for (const tech of recommendations) {
    for (const fm of tech.fundingMatches) {
      if (!allSchemes.has(fm.schemeId)) {
        allSchemes.set(fm.schemeId, { name: fm.name, agency: fm.implementingAgency, subsidy: fm.subsidyPct, status: fm.status });
      }
    }
  }

  if (allSchemes.size > 0) {
    y += 8;
    y = checkPage(doc, y, 20, pageNum);
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('Applicable Funding Schemes', MARGIN, y);
    y += 8;

    doc.setFontSize(8);
    for (const [, scheme] of allSchemes) {
      y = checkPage(doc, y, 10, pageNum);
      doc.setTextColor(30, 41, 59);
      doc.text(`${scheme.name} (${scheme.agency})`, MARGIN, y);
      doc.setTextColor(100, 116, 139);
      const extra = [scheme.status];
      if (scheme.subsidy != null) extra.push(`Subsidy: ${scheme.subsidy}%`);
      doc.text(extra.join(' · '), MARGIN + 4, y + 4);
      y += 10;
    }
  }

  addFooter(doc, pageNum.val);
  doc.save('Emission-Reduction-Plan.pdf');
}
